@echo off
cd /d "%~dp0"
echo [1/3] Trigger WordPress generation (cloud)...
node triggerGenerate.js
echo [2/3] Wait for generation to finish...
timeout /t 150 /nobreak >nul
echo [3/3] Mirror to Tistory...
node tistoryMirror.js
