@echo off
cd /d "%~dp0"
echo [1/3] Trigger WordPress generation (cloud)...
node triggerGenerate.js
echo [2/3] Wait ~150s for generation to finish...
ping -n 151 127.0.0.1 >nul
echo [3/3] Mirror to Tistory...
node tistoryMirror.js
